// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLl9IlBwvVKXk3-TTLDJvQSWEzJKZX_Pk',
    appId: '1:566127038120:web:144163bb84a7bc15b37c9d',
    messagingSenderId: '566127038120',
    projectId: 'huggets-app',
    authDomain: 'huggets-app.firebaseapp.com',
    storageBucket: 'huggets-app.firebasestorage.app',
    measurementId: 'G-8M8Z304HVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYSDEPQ1ZgwHGgsBAoqju3tvdZ1ubYiwU',
    appId: '1:566127038120:android:e6e8471ad11056d1b37c9d',
    messagingSenderId: '566127038120',
    projectId: 'huggets-app',
    storageBucket: 'huggets-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS1yGGLwktijxBNu1mbGfIi0RUsfmdK-Q',
    appId: '1:566127038120:ios:a9e6a5828a065625b37c9d',
    messagingSenderId: '566127038120',
    projectId: 'huggets-app',
    storageBucket: 'huggets-app.firebasestorage.app',
    iosBundleId: 'com.example.huggetsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS1yGGLwktijxBNu1mbGfIi0RUsfmdK-Q',
    appId: '1:566127038120:ios:a9e6a5828a065625b37c9d',
    messagingSenderId: '566127038120',
    projectId: 'huggets-app',
    storageBucket: 'huggets-app.firebasestorage.app',
    iosBundleId: 'com.example.huggetsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLl9IlBwvVKXk3-TTLDJvQSWEzJKZX_Pk',
    appId: '1:566127038120:web:8b9117ba08ebccb7b37c9d',
    messagingSenderId: '566127038120',
    projectId: 'huggets-app',
    authDomain: 'huggets-app.firebaseapp.com',
    storageBucket: 'huggets-app.firebasestorage.app',
    measurementId: 'G-KPGD843EW5',
  );
}
